//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineTemplate) DeepCopyInto(out *MachineTemplate) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineTemplate.
func (in *MachineTemplate) DeepCopy() *MachineTemplate {
	if in == nil {
		return nil
	}
	out := new(MachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolLimits) DeepCopyInto(out *NodePoolLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolLimits.
func (in *NodePoolLimits) DeepCopy() *NodePoolLimits {
	if in == nil {
		return nil
	}
	out := new(NodePoolLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithClaim) DeepCopyInto(out *NodeSmithClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithClaim.
func (in *NodeSmithClaim) DeepCopy() *NodeSmithClaim {
	if in == nil {
		return nil
	}
	out := new(NodeSmithClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithClaim) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithClaimList) DeepCopyInto(out *NodeSmithClaimList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSmithClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithClaimList.
func (in *NodeSmithClaimList) DeepCopy() *NodeSmithClaimList {
	if in == nil {
		return nil
	}
	out := new(NodeSmithClaimList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithClaimList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithClaimRequirements) DeepCopyInto(out *NodeSmithClaimRequirements) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithClaimRequirements.
func (in *NodeSmithClaimRequirements) DeepCopy() *NodeSmithClaimRequirements {
	if in == nil {
		return nil
	}
	out := new(NodeSmithClaimRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithClaimSpec) DeepCopyInto(out *NodeSmithClaimSpec) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = new(NodeSmithClaimRequirements)
		**out = **in
	}
	if in.TerminationGracePeriod != nil {
		in, out := &in.TerminationGracePeriod, &out.TerminationGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithClaimSpec.
func (in *NodeSmithClaimSpec) DeepCopy() *NodeSmithClaimSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSmithClaimSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithClaimStatus) DeepCopyInto(out *NodeSmithClaimStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithClaimStatus.
func (in *NodeSmithClaimStatus) DeepCopy() *NodeSmithClaimStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSmithClaimStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithControlPlane) DeepCopyInto(out *NodeSmithControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithControlPlane.
func (in *NodeSmithControlPlane) DeepCopy() *NodeSmithControlPlane {
	if in == nil {
		return nil
	}
	out := new(NodeSmithControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithControlPlaneList) DeepCopyInto(out *NodeSmithControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSmithControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithControlPlaneList.
func (in *NodeSmithControlPlaneList) DeepCopy() *NodeSmithControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(NodeSmithControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithControlPlaneSpec) DeepCopyInto(out *NodeSmithControlPlaneSpec) {
	*out = *in
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithControlPlaneSpec.
func (in *NodeSmithControlPlaneSpec) DeepCopy() *NodeSmithControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSmithControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithControlPlaneStatus) DeepCopyInto(out *NodeSmithControlPlaneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithControlPlaneStatus.
func (in *NodeSmithControlPlaneStatus) DeepCopy() *NodeSmithControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSmithControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithPool) DeepCopyInto(out *NodeSmithPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithPool.
func (in *NodeSmithPool) DeepCopy() *NodeSmithPool {
	if in == nil {
		return nil
	}
	out := new(NodeSmithPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithPoolList) DeepCopyInto(out *NodeSmithPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSmithPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithPoolList.
func (in *NodeSmithPoolList) DeepCopy() *NodeSmithPoolList {
	if in == nil {
		return nil
	}
	out := new(NodeSmithPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithPoolSpec) DeepCopyInto(out *NodeSmithPoolSpec) {
	*out = *in
	out.Limits = in.Limits
	in.MachineTemplate.DeepCopyInto(&out.MachineTemplate)
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(ScaleUpPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(ScaleDownPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithPoolSpec.
func (in *NodeSmithPoolSpec) DeepCopy() *NodeSmithPoolSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSmithPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithPoolStatus) DeepCopyInto(out *NodeSmithPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastScaleActivity != nil {
		in, out := &in.LastScaleActivity, &out.LastScaleActivity
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithPoolStatus.
func (in *NodeSmithPoolStatus) DeepCopy() *NodeSmithPoolStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSmithPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithProvider) DeepCopyInto(out *NodeSmithProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithProvider.
func (in *NodeSmithProvider) DeepCopy() *NodeSmithProvider {
	if in == nil {
		return nil
	}
	out := new(NodeSmithProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithProviderList) DeepCopyInto(out *NodeSmithProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeSmithProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithProviderList.
func (in *NodeSmithProviderList) DeepCopy() *NodeSmithProviderList {
	if in == nil {
		return nil
	}
	out := new(NodeSmithProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeSmithProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithProviderSpec) DeepCopyInto(out *NodeSmithProviderSpec) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
	if in.Proxmox != nil {
		in, out := &in.Proxmox, &out.Proxmox
		*out = new(ProxmoxProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalSettings != nil {
		in, out := &in.AdditionalSettings, &out.AdditionalSettings
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithProviderSpec.
func (in *NodeSmithProviderSpec) DeepCopy() *NodeSmithProviderSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSmithProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSmithProviderStatus) DeepCopyInto(out *NodeSmithProviderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSmithProviderStatus.
func (in *NodeSmithProviderStatus) DeepCopy() *NodeSmithProviderStatus {
	if in == nil {
		return nil
	}
	out := new(NodeSmithProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxNIC) DeepCopyInto(out *ProxmoxNIC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxNIC.
func (in *ProxmoxNIC) DeepCopy() *ProxmoxNIC {
	if in == nil {
		return nil
	}
	out := new(ProxmoxNIC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxOption) DeepCopyInto(out *ProxmoxOption) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxOption.
func (in *ProxmoxOption) DeepCopy() *ProxmoxOption {
	if in == nil {
		return nil
	}
	out := new(ProxmoxOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxProviderSpec) DeepCopyInto(out *ProxmoxProviderSpec) {
	*out = *in
	if in.NodeWhitelist != nil {
		in, out := &in.NodeWhitelist, &out.NodeWhitelist
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VMIDRange != nil {
		in, out := &in.VMIDRange, &out.VMIDRange
		*out = new(VMIDRange)
		**out = **in
	}
	if in.NetworkInterfaces != nil {
		in, out := &in.NetworkInterfaces, &out.NetworkInterfaces
		*out = make([]ProxmoxNIC, len(*in))
		copy(*out, *in)
	}
	if in.VMOptions != nil {
		in, out := &in.VMOptions, &out.VMOptions
		*out = make([]ProxmoxOption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxProviderSpec.
func (in *ProxmoxProviderSpec) DeepCopy() *ProxmoxProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDownPolicy) DeepCopyInto(out *ScaleDownPolicy) {
	*out = *in
	if in.StabilizationWindow != nil {
		in, out := &in.StabilizationWindow, &out.StabilizationWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDownPolicy.
func (in *ScaleDownPolicy) DeepCopy() *ScaleDownPolicy {
	if in == nil {
		return nil
	}
	out := new(ScaleDownPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleUpPolicy) DeepCopyInto(out *ScaleUpPolicy) {
	*out = *in
	if in.StabilizationWindow != nil {
		in, out := &in.StabilizationWindow, &out.StabilizationWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleUpPolicy.
func (in *ScaleUpPolicy) DeepCopy() *ScaleUpPolicy {
	if in == nil {
		return nil
	}
	out := new(ScaleUpPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMIDRange) DeepCopyInto(out *VMIDRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMIDRange.
func (in *VMIDRange) DeepCopy() *VMIDRange {
	if in == nil {
		return nil
	}
	out := new(VMIDRange)
	in.DeepCopyInto(out)
	return out
}
